2
lkhalilova/lkhalilova.github.io pull request #2
Opened 2023-04-11 19:43 UTC by lkhalilova

Я поки що буду на цей репозиторій пушити,потім,якщо буде потрібно,перенесу на 1й,де всі інші дз)

2023-04-14 17:36 UTC, klymenok requested changes

2023-04-14 17:36 UTC, klymenok commented on Flask_homework/views.py
> +            for key, value in request.args.items():
Параметрів може бути більше ніж один, а тут ви берете до уваги лише перший. Замініть це краще на `number = request.args.get('count')`

2023-04-14 17:36 UTC, klymenok commented on Flask_homework/views.py
> +            for key, value in request.args.items():
Параметрів може бути більше ніж один, а тут ви берете до уваги лише перший. Замініть це краще на `number = request.args.get('count')`

2023-04-14 17:36 UTC, klymenok commented on Flask_homework/views.py
> +            for key, value in request.args.items():
Параметрів може бути більше ніж один, а тут ви берете до уваги лише перший. Замініть це краще на `number = request.args.get('count')`

2023-04-21 15:46 UTC, klymenok requested changes

2023-04-21 15:46 UTC, klymenok commented on .env
цей файл не потрібно пушити на git. Видаліть його

2023-04-21 15:46 UTC, klymenok commented on instance/flask_database.sqlite
Не потрібно пушити базу даних на git. Видаліть цей файл

2023-04-21 15:46 UTC, klymenok commented on Flask_homework/views.py
> +
Видаліть зайві пусті рядки, залиште тільки один

2023-04-25 17:24 UTC, lkhalilova commented on .env
А як .env міг запушитись коли він в git ігнорі?

2023-04-25 17:56 UTC, klymenok commented on .env
Він міг бути запушений до створення gitignore, або невірно налаштований

2023-05-07 17:08 UTC, closed without merging